import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";

const VazirFont = Vazirmatn({
  variable: "--font-vazir",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${VazirFont.variable} font-[family-name:var(--font-vazir)] antialiased`}>{children}</body>
    </html>
  );
}
